In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

### Create & Read

#### 1D Array

In [8]:
arr1 = np.array([1, 2, 3, 4 , 5])
arr1

array([1, 2, 3, 4, 5])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.shape

(5,)

In [11]:
arr1.dtype

dtype('int32')

In [12]:
arr1.ndim

1

In [13]:
arr1.size

5

#### 2D Array

In [15]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape # (row, col)

(2, 3)

In [18]:
arr2.dtype

dtype('int32')

In [19]:
arr1.size

5

#### 3D Array

In [23]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]],[[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [24]:
arr3.ndim

3

In [25]:
arr3.shape # ( nº of layers, rows, col )

(3, 2, 3)

In [26]:
arr3.size

18

### Create random array

In [27]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.02329214, 0.32002707, 0.63827756],
        [0.76595377, 0.31804329, 0.21553118]],

       [[0.63153276, 0.86551323, 0.12665015],
        [0.08418408, 0.18687476, 0.73270021]],

       [[0.51738605, 0.55073479, 0.35848999],
        [0.81636959, 0.54175681, 0.73709252]]])

In [28]:
randomArr.dtype

dtype('float64')

In [32]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
zeroes.ndim

3

In [34]:
full = np.full((3, 2, 3), 8)  # Fiil with number 8
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [35]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [37]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [38]:
arr3[0][0][2]

5

In [39]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [40]:
arr3[-1] # access las item in the array

array([[1, 4, 5],
       [6, 7, 4]])

In [41]:
arr3[1][0][1]

5

In [42]:
arr3[1, 0, 1]

5

### Update & Delete

In [43]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [44]:
a1

array([[[6.79817462e-01, 3.79959934e-02],
        [7.01653897e-01, 7.38459683e-01],
        [6.03636903e-01, 2.76176935e-01]],

       [[4.90858956e-01, 7.80317523e-01],
        [1.07313717e-01, 9.07519349e-01],
        [7.38742733e-04, 3.23002716e-01]]])

In [45]:
a2

array([[[0.51247207, 0.29525075],
        [0.16003863, 0.1557629 ],
        [0.82866029, 0.28381823]],

       [[0.69167725, 0.89754676],
        [0.65879454, 0.49752559],
        [0.89547802, 0.10165714]]])

#### Basic Math Operations

In [46]:
np.add(a1, a2)

array([[[1.19228953, 0.33324674],
        [0.86169253, 0.89422259],
        [1.43229719, 0.55999517]],

       [[1.18253621, 1.67786428],
        [0.76610826, 1.40504494],
        [0.89621676, 0.42465985]]])

In [47]:
np.subtract(a1, a2)

array([[[ 0.16734539, -0.25725476],
        [ 0.54161526,  0.58269678],
        [-0.22502339, -0.0076413 ]],

       [[-0.2008183 , -0.11722923],
        [-0.55148082,  0.40999376],
        [-0.89473927,  0.22134558]]])

In [48]:
np.divide(a1, a2)

array([[[1.32654540e+00, 1.28690591e-01],
        [4.38427819e+00, 4.74092137e+00],
        [7.28449172e-01, 9.73076787e-01]],

       [[7.09664739e-01, 8.69389275e-01],
        [1.62894060e-01, 1.82406566e+00],
        [8.24970260e-04, 3.17737373e+00]]])

In [49]:
np.multiply(a1, a2)

array([[[3.48387460e-01, 1.12183455e-02],
        [1.12291732e-01, 1.15024625e-01],
        [5.00209932e-01, 7.83840499e-02]],

       [[3.39515973e-01, 7.00371460e-01],
        [7.06976906e-02, 4.51514101e-01],
        [6.61527878e-04, 3.28355313e-02]]])

#### Statistical Operations

In [50]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [51]:
sqrt

5.0

In [52]:
abs

2

In [53]:
power

256

In [54]:
log

3.2188758248682006

In [55]:
mins

0.0007387427332200547

In [56]:
maxs

0.8975467550812525

#### Update

In [57]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [58]:
arr3[0, 0, 2]  = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [60]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [62]:
# Reshape
arr3.shape

(3, 2, 3)

In [64]:
arr3_reshape = arr3.reshape((2, 3, 3))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [65]:
arr3_reshape.shape

(2, 3, 3)

In [66]:
arr3_reshape = arr3.reshape((2, 3, -1)) # we can recshape ignoring the last dimension
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

### Appending & Inserting

In [67]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [68]:
# Create a new array
new_array = np.ones([3, 2, 3])
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [69]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [70]:
appd = np.append(zeroes, new_array, axis=1) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
# Insert

In [71]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [72]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [74]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [75]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.66788204, 0.89042451, 0.77283849],
        [0.15772441, 0.99144201, 0.88033899]],

       [[0.0285845 , 0.11583285, 0.62394956],
        [0.49042848, 0.58500883, 0.55452754]],

       [[0.75682139, 0.28913076, 0.88417194],
        [0.5798142 , 0.67404841, 0.27464712]]])

In [77]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [78]:
arr5

array([[[0.15772441, 0.99144201, 0.88033899]],

       [[0.49042848, 0.58500883, 0.55452754]],

       [[0.5798142 , 0.67404841, 0.27464712]]])

In [79]:
np.save("new_array", arr5 ) # write the np array in a npy file named 'new_array'

In [81]:
np.load("new_array.npy")

array([[[0.15772441, 0.99144201, 0.88033899]],

       [[0.49042848, 0.58500883, 0.55452754]],

       [[0.5798142 , 0.67404841, 0.27464712]]])